--Q1. what is the total revenue generated by male vs. female customers?
select "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
group by "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT "Customer ID",
       "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >=
      (SELECT AVG("Purchase Amount (USD)")
       FROM customer);
	   
__ Q3. Which are the top 5 products with the highest average  review rating?

SELECT "Item Purchased",
      ROUND (AVG("Review Rating"::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amount between Standard and Express Shipping.

SELECT "Shipping Type",
       ROUND(AVG("Purchase Amount (USD)"), 2) AS "Average Purchase Amount"
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.

SELECT "Subscription Status",
       COUNT("Customer ID") AS total_customers,
       ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_spend,
       ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT "Item Purchased",
       ROUND(
           100.0 * SUM(
               CASE
                   WHEN "Discount Applied" = 'Yes' THEN 1
                   ELSE 0
               END
           ) / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal

SELECT
    CASE
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer
GROUP BY
    CASE
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END;

-- Q8. What are the top 3 most purchased products within each category?

SELECT
    "Category",
    "Item Purchased",
    total_orders,
    item_rank
FROM (
    SELECT
        "Category",
        "Item Purchased",
        COUNT("Customer ID") AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT("Customer ID") DESC
        ) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
) AS ranked_products
WHERE item_rank <= 3
ORDER BY "Category", item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    "Subscription Status",
    COUNT(*) AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

-- Q10. What is the revenue contribution of each age group?

SELECT
    CASE
        WHEN "Age" < 20 THEN 'Under 20'
        WHEN "Age" BETWEEN 20 AND 29 THEN '20-29'
        WHEN "Age" BETWEEN 30 AND 39 THEN '30-39'
        WHEN "Age" BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS age_group,

    SUM("Purchase Amount (USD)") AS total_revenue

FROM customer

GROUP BY
    CASE
        WHEN "Age" < 20 THEN 'Under 20'
        WHEN "Age" BETWEEN 20 AND 29 THEN '20-29'
        WHEN "Age" BETWEEN 30 AND 39 THEN '30-39'
        WHEN "Age" BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END

ORDER BY total_revenue DESC;


